[options]
addons_path = /home/reyh/projects/odoo/addons,/home/reyh/Xenna_Magang_/modules
data_dir = /home/reyh/Xenna_Magang_/data
admin_passwd = 123
http_interface = localhost
http_port = 8069
longpolling_port = 3004
; dbfilter = vania*
; disable the weekly publisher-warranty call-home (default: services.odoo.com)
publisher_warranty_url = http://localhost:1/
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_maxconn = 200
dev_mode = reload
limit_memory_hard = False
limit_memory_soft = False
limit_time_real = 120000
limit_time_cpu = 120000
